import React from 'react'
import Container from 'react-bootstrap/Container'
import '../css/writing.css'
import { LinkContainer } from "react-router-bootstrap";
import Breadcrumb from 'react-bootstrap/Breadcrumb'

class Thesis extends React.Component {    
	render() {
		return (
			<div className='thesis'>
                <Breadcrumb>
                    <LinkContainer to="/writing">
                        <Breadcrumb.Item>Writing</Breadcrumb.Item>
                    </LinkContainer>
                    <Breadcrumb.Item active>Consciousness and Self-Awareness</Breadcrumb.Item>
                </Breadcrumb>
                
                {/* page content */}
                <Container className="writing-content">
                    <h1 className="writing-title">Can Brainless Jellyfish Or Ants Be Self-Aware?</h1>
                    <h4>Abstract</h4>
                    <p>Consciousness and self-awareness in animals is a long-debated topic and one that has yet had a definitive answer. For animal consciousness, it was declared by the Cambridge Declaration on Consciousness (2012) that all animals are conscious. In addition to this paper providing evidence that consciousness does not arise from a specific brain region, it will also explain the relationship between consciousness and self-awareness. For example, Cleeremans (2011) suggested that consciousness arises from a being knowing it is in a certain state and caring about that state, that is to say, the being is conscious if it is aware of its subjective experience. If this is the case, then consciousness requires some sort of awareness. However, this paper will also attempt to explain why consciousness and self-awareness are not necessary for one another, but instead, work together as an integrated system. Due to this, it is important to discuss theories of both consciousness and self-awareness and highlight the similarities. One similarity is that both consciousness and self-awareness are on a gradient scale. That is, there are different degrees of consciousness and self-awareness; one animal could be more conscious than another.</p>
                    <p>To explain how consciousness arises in animals, we will delve into the dreams of rats and eels. Furthermore, we will go into detail of what self-awareness is, using the three types of self-awareness provide by Degraza (2009); bodily self-awareness, social self-awareness, and introspective self-awareness. A few examples ranging from mammals to mollusc will be used to provide evidence of self-awareness in animals. Most of them involve the mirror test, however, as later shown, it is not a good way to define which animals experience self-awareness and which do not. One constraint of the mirror test is that it would not work on animals that rely heavily on senses other than sight. Due to this, a more recent test called Sniff Test of Self-Recognition (Gatti, 2015) was developed. In conclusion, we find that all animals are likely to experience self-awareness, although the level of self-awareness will differ. This is strongly supported by Degraza (2009), where his theory claims that as long as the animal is aware of its body, it has at least a basic level of introspective self-awareness. This leads to an animal having both bodily self-awareness and introspective self-awareness.</p>
                    
                    <h4>Introduction</h4>
                    <p>This paper is going to argue about whether all animals are self-aware, considering that they are all conscious, as agreed upon by The Cambridge Declaration on Consciousness (2012). To understand this, theories and differences between consciousness and self-awareness will be discussed. This will provide insight into the tight link between the two. Moreover, it will pave a deeper argument into whether consciousness and self-awareness arise from the sum of certain brain regions, a certain brain region or neither of the two. </p>
                    <p>Following this, there will be a discussion on animals and consciousness, where dreaming will be delved into. Afterwards, we will look into animals and self-awareness, this will include evidences, and the current popular method of testing self-awareness in animals; the mirror test. In order to validate most evidences, we will have to review the mirror test. Hence, following this is a detailed look into the mirror test, discussing its usefulness as a test as well as its downfalls. This will provide further insight into whether past research has any grounds for animal self-awareness. Furthermore, we will look into other methods of testing self-awareness. Lastly, while there is strong evidence of self-awareness in mammals, this paper will also delve deeper into birds, insects and molluscs, as they have a very different brain structure, one that excludes the brain areas often associated to consciousness. </p>

                    <h4>Consciousness and Self-Awareness</h4>
                    <p>Firstly, we will discuss consciousness. Consciousness has been a long-debated topic, ranging from what it does (the functional problem) to what it is (the nature problem). One of the earliest works comes from Descartes&rsquo;s Dualism theory, which is that the mind and body are two separate entities (Descartes, 1641). However, that theory has had a long battle of arguments against it. More recently, it was believed that consciousness is the by-product of some parts of our brain, mainly the neocortex (Butler, Manger, Lindahl,&amp; Århem, 2005; Bogen, 1995) or, more specifically, the claustrum (Crick, &amp; Koch, 2005), which is located in the neocortex.</p>
                    <p>However, there are newer studies that disagree with the correlation between brain regions and consciousness, as they found cases where participants lose consciousness while those brain regions are still stimulated (Koch, 2012). It can then be concluded that while the claustrum or the neocortex plays a role, it is not what gives rise to consciousness. Furthermore, Cleeremans (2011) mentioned about the plasticity of the human brain and consciousness, implying that consciousness is not the result of any specific parts of the brain but rather from a process of learning. This is also evidenced by the fact that animals other than mammals do not have a neocortex, and yet some of them, such as birds and insects, have been deemed conscious.</p>
                    <p>In Cleeremans&rsquo; paper, he describes consciousness as the result of having knowledge of their internal states and having emotional value attached to those states, and this is done through learning, the action of describing and re-describing to itself. That is, consciousness arises from being aware and having emotions (since it is a necessary definition for subjective experience). He also implies that while emotion is necessary, it is not sufficient for consciousness.</p>
                    <p>Before moving on, it is important to note that consciousness and self-awareness have been closely correlated, often times consciousness is considered necessary for self-awareness however, the relationship does not go the other way. This is a slight contradiction to Cleeremans&rsquo; description of consciousness where he describes self-awareness as one of the conditions for consciousness. However, it is easier to understand it by defining their relationship as an integrated system. That is, while consciousness is necessary for self- awareness, the two of them works similarly to how consciousness works with the global space in the Global Workspace Theory (GWT). GWT implies that rather than consciousness being a module, it is part of a process required to bring to light which module is salient for the global space. In the same way, rather than one being a part of the other, they work in an integrated fashion to bring consciousness to an individual. This is further shown in individuals with anosognosia, the loss of self-awareness.</p>
                    <p>According to Moro et al (2011) as well as Vallar &amp; Ronchi (2006), self-awareness is linked to the parietal lobe or a lesion in the frontal-temporal-parietal area, since it is often linked to individuals with anosognosia. There are also other papers that show a similar link between brain injuries and loss of self-awareness (Bach &amp; David, 2006; Prigatano, 2005). As demonstrated by those individuals, despite the fact that they are conscious, they are not self- aware. Hence, self-awareness is not necessary for consciousness. This also provides further evidence that the two are more likely to be part of an integrated system than a causal relationship.</p>
                
                    <h4>Animal and Consciousness</h4>
                    <p>While it is agreed upon that all humans have consciousness, the debate around whether animals have consciousness has been around for a long time. Even though it is not clear yet where consciousness might stem from, a group of notable scientist, including cognitive neuroscientists, and computational neuroscientists, has signed The Cambridge Declaration on Consciousness (2012). This declaration states that humans are not unique in the ability to have consciousness, instead, all animals are capable and do have consciousness. It further outlines that although animals are unable to communicate their thoughts and internal states, there is evidence that they all possess the neurological substrate that is correlated to consciousness.</p>
                    <p>This is further supported by Mashour and Alkire (2013), who did a cross-analysis between many disciplines including evolutionary neurobiology, anesthesiology and animal psychology. They agreed that while there is strong evidence that all animals have consciousness, the differences lie in how rich each animal experience consciousness.</p>
                    <p>Due to the differences in the experience of consciousness, for this paper, consciousness would need to be defined. While there is no agreed upon definition, I will be defining consciousness as it is implied by The Cambridge Declaration on Consciousness, that is, a being is conscious if it has a conscious state. While there are several conscious states to choose from, we would be using the qualitative state for this definition. The qualitative state involves the being to be able to experience qualitative or experiential properties, also known as qualia (Van Gulick, 2018). Since this definition requires subjective experience or qualia in order to be conscious, it converges with Cleeremans&rsquo; argument.</p>
                    
                    <br></br>
                    <h5>
                        If interested,  
                        <span> 
                            <a href = "mailto:carleen.thio@gmail.com?subject=Requesting Brainless Jellyfish Copy!"> email me </a>
                        </span>
			             for the rest
                    </h5>
                    <br></br>
                </Container>
			</div>
		);
	}
}
export default Thesis